// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEuGN2owZqR7U9EsnY4fmETDvSq14i01s',
    appId: '1:919109658740:web:90824156ae699050fe0921',
    messagingSenderId: '919109658740',
    projectId: 'lggf6fl3p8gb2ts3i2o9zt1oicc1ga',
    authDomain: 'lggf6fl3p8gb2ts3i2o9zt1oicc1ga.firebaseapp.com',
    storageBucket: 'lggf6fl3p8gb2ts3i2o9zt1oicc1ga.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyflc8KoFCPbkHFLHDEHV-PcQaIRd4GhY',
    appId: '1:919109658740:android:2bdea87696d6cc15fe0921',
    messagingSenderId: '919109658740',
    projectId: 'lggf6fl3p8gb2ts3i2o9zt1oicc1ga',
    storageBucket: 'lggf6fl3p8gb2ts3i2o9zt1oicc1ga.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAedk-rz7Owzx8s03UQAJ67-keYLDOiHm0',
    appId: '1:919109658740:ios:2de01e4ae84eb786fe0921',
    messagingSenderId: '919109658740',
    projectId: 'lggf6fl3p8gb2ts3i2o9zt1oicc1ga',
    storageBucket: 'lggf6fl3p8gb2ts3i2o9zt1oicc1ga.firebasestorage.app',
    iosBundleId: 'com.varma.studentrank',
  );
}
